In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('Data\\Fortune_10.csv')

df1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [3]:
# series

scaler_s = pd.Series(1)
print(scaler_s)

0    1
dtype: int64

In [4]:
series_2 = pd.Series(
    [1, 2, 3, 4],
    index=['a', 'b', 'c', 'd'],
    dtype=float,
    name='Data'
)

print(series_2)

a    1.0
b    2.0
c    3.0
d    4.0
Name: Data, dtype: float64

In [5]:
# index to series

sr_index = pd.Series([1,2,3,4,5])
print(sr_index)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
sr_index[3]

np.int64(4)

In [7]:
min(sr_index)

1

In [8]:
max(sr_index)

5

In [9]:
sr_index[sr_index < 2]

0    1
dtype: int64

In [10]:
sr_1 = pd.Series([1,2,3,4])
sr_2 = pd.Series([5,6,7,8])

print(sr_1)
print(sr_2)

sr_sum = sr_1 + sr_2
print(sr_sum)

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64
0     6
1     8
2    10
3    12
dtype: int64

In [11]:
df1 = pd.read_csv('Data\\Fortune_10.csv')

df1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [12]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , nrows=1)

df1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%

In [13]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , usecols=[1])

df1

              Name
0          Lamtone
1        Stripfind
2  Canecorporation
3         Mattouch
4        Techdrill
5         Techline
6          Cityace
7   Kayelectronics
8          Ganzlax
9      Trantraxlax

In [14]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , usecols=[1,3,5])

df1

              Name  Inception           Expenses
0          Lamtone       2009  6,482,465 Dollars
1        Stripfind       2010    916,455 Dollars
2  Canecorporation       2012  7,591,189 Dollars
3         Mattouch       2013  7,429,377 Dollars
4        Techdrill       2009  7,435,363 Dollars
5         Techline       2006  5,470,303 Dollars
6          Cityace       2010  6,249,498 Dollars
7   Kayelectronics       2009  3,878,113 Dollars
8          Ganzlax       2011                NaN
9      Trantraxlax       2011  5,635,276 Dollars

In [15]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , skiprows =1)

df1

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [16]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , skiprows=[1,3,4])

df1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
2,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
3,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
4,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
5,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
6,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [17]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , index_col='ID')

df1

,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [18]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , index_col='Name')

df1

,ID,Industry,Inception,Revenue,Expenses,Profit,Growth
Name,,,,,,,
Lamtone,1,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
Stripfind,2,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
Canecorporation,3,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
Mattouch,4,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
Techdrill,5,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
Techline,6,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
Cityace,7,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
Kayelectronics,8,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
Ganzlax,9,IT Services,2011,"$14,001,180",NaN,11901180,18%
Trantraxlax,10,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [19]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , index_col=3)

df1

,ID,Name,Industry,Revenue,Expenses,Profit,Growth
Inception,,,,,,,
2009,1,Lamtone,IT Services,"$11,757,018","6,482,465 Dollars",5274553,30%
2010,2,Stripfind,Financial Services,"$12,329,371","916,455 Dollars",11412916,20%
2012,3,Canecorporation,Health,"$10,597,009","7,591,189 Dollars",3005820,7%
2013,4,Mattouch,IT Services,"$14,026,934","7,429,377 Dollars",6597557,26%
2009,5,Techdrill,Health,"$10,573,990","7,435,363 Dollars",3138627,8%
2006,6,Techline,Health,"$13,898,119","5,470,303 Dollars",8427816,23%
2010,7,Cityace,Health,"$9,254,614","6,249,498 Dollars",3005116,6%
2009,8,Kayelectronics,Health,"$9,451,943","3,878,113 Dollars",5573830,4%
2011,9,Ganzlax,IT Services,"$14,001,180",NaN,11901180,18%
2011,10,Trantraxlax,Government Services,"$11,088,336","5,635,276 Dollars",5453060,7%

## Header

In [20]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , header=1)

df1

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [21]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , names=['A','B'])

df1

,,,,,,A,B
ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",nan,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [22]:
df1 = pd.read_csv('Data\\Fortune_10.csv' , dtype={'ID' : 'float64' , 'profit' : 'float64'})

df1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4.0,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5.0,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6.0,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

## NAN values

# N/A ,#N/A

In [23]:
df2 = pd.read_csv('Data//Fortune_10 - Copy.csv')

df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [24]:
df2 = pd.read_csv('Data//Fortune_10 - Copy.csv' , na_values= 'not avellable')

df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [25]:
df2 = pd.read_csv('Data//Fortune_10 - Copy.csv' , na_values= {'Revenue' : 'not values'})

df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [26]:
df2 = pd.read_csv('Data//Fortune_10 - Copy.csv' , keep_default_na= True)

df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [27]:
df2 = pd.read_csv('Data//Fortune_10 - Copy.csv' , na_filter='False')

df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [28]:
df2.isnull()

      ID   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  False  False     False      False    False     False   False   False
1  False  False     False      False    False     False   False   False
2  False  False     False      False    False     False   False   False
3  False  False     False      False    False     False   False   False
4  False  False     False      False    False     False   False   False
5  False  False     False      False    False     False   False   False
6  False  False     False      False    False     False   False   False
7  False  False     False      False    False     False   False   False
8  False  False     False      False    False      True   False   False
9  False  False     False      False    False     False   False   False

In [29]:
df2.notnull()

     ID  Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  True  True      True       True     True      True    True    True
1  True  True      True       True     True      True    True    True
2  True  True      True       True     True      True    True    True
3  True  True      True       True     True      True    True    True
4  True  True      True       True     True      True    True    True
5  True  True      True       True     True      True    True    True
6  True  True      True       True     True      True    True    True
7  True  True      True       True     True      True    True    True
8  True  True      True       True     True     False    True    True
9  True  True      True       True     True      True    True    True

In [30]:
df2.notnull().sum()

ID           10
Name         10
Industry     10
Inception    10
Revenue      10
Expenses      9
Profit       10
Growth       10
dtype: int64

In [31]:
ser = pd.Series([1, 2, 3, np.nan, 4, np.nan])
ser

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [32]:
ser.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [33]:
df3 = pd.read_csv('Data//Fortune_5 nan values.csv')

df3

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df3.dropna()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [35]:
df3.dropna(axis= 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
df3.dropna(axis= 0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [37]:
df3.dropna(how = 'any')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [38]:
df3.dropna(axis= 1,how= 'any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
df3.dropna(how= 'all')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [40]:
df3.dropna(thresh= 0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df3.dropna(thresh = 2)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [42]:
df3.dropna(subset= ['Expenses'])

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [43]:
df3.fillna({'Expenses' : 'none' , 'Profit' : 55})

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",none,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",55.0,8%
5,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
6,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
7,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
8,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
9,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN

In [44]:
df3.ffill

<bound method NDFrame.ffill of     ID             Name            Industry  Inception       Revenue  \
0  1.0          Lamtone         IT Services     2009.0  $11,757,018
1  2.0        Stripfind  Financial Services     2010.0  $12,329,371
2  3.0  Canecorporation              Health     2012.0  $10,597,009
3  4.0         Mattouch         IT Services     2013.0  $14,026,934
4  5.0        Techdrill              Health     2009.0  $10,573,990
5  NaN              NaN                 NaN        NaN           NaN
6  NaN              NaN                 NaN        NaN           NaN
7  NaN              NaN                 NaN        NaN           NaN
8  NaN              NaN                 NaN        NaN           NaN
9  NaN              NaN                 NaN        NaN           NaN

            Expenses      Profit Growth
0  6,482,465 Dollars   5274553.0    30%
1    916,455 Dollars  11412916.0    20%
2                NaN   3005820.0     7%
3  7,429,377 Dollars   6597557.0    26%
4  7,435,363 Dollars         NaN     8%
5                NaN         NaN    NaN
6                NaN         NaN    NaN
7                NaN         NaN    NaN
8                NaN         NaN    NaN
9                NaN         NaN    NaN  >

In [45]:
df3.bfill

<bound method NDFrame.bfill of     ID             Name            Industry  Inception       Revenue  \
0  1.0          Lamtone         IT Services     2009.0  $11,757,018
1  2.0        Stripfind  Financial Services     2010.0  $12,329,371
2  3.0  Canecorporation              Health     2012.0  $10,597,009
3  4.0         Mattouch         IT Services     2013.0  $14,026,934
4  5.0        Techdrill              Health     2009.0  $10,573,990
5  NaN              NaN                 NaN        NaN           NaN
6  NaN              NaN                 NaN        NaN           NaN
7  NaN              NaN                 NaN        NaN           NaN
8  NaN              NaN                 NaN        NaN           NaN
9  NaN              NaN                 NaN        NaN           NaN

            Expenses      Profit Growth
0  6,482,465 Dollars   5274553.0    30%
1    916,455 Dollars  11412916.0    20%
2                NaN   3005820.0     7%
3  7,429,377 Dollars   6597557.0    26%
4  7,435,363 Dollars         NaN     8%
5                NaN         NaN    NaN
6                NaN         NaN    NaN
7                NaN         NaN    NaN
8                NaN         NaN    NaN
9                NaN         NaN    NaN  >

In [46]:
df3.ffill(limit=2)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","916,455 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
5,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
6,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## replace

In [47]:
df3.replace('IT services', 'AI/ML')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df3.replace(10,15)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df3.replace('[A - Za - z]' , 0 , regex = True)

    ID       Name Industry  Inception Revenue Expenses      Profit Growth
0  1.0          0        0     2009.0       0        0   5274553.0    30%
1  2.0  Stripfind        0     2010.0       0        0  11412916.0    20%
2  3.0          0        0     2012.0       0      NaN   3005820.0     7%
3  4.0          0        0     2013.0       0        0   6597557.0    26%
4  5.0  Techdrill        0     2009.0       0        0         NaN     8%
5  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN
6  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN
7  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN
8  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN
9  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN

In [50]:
df3.dtypes

ID           float64
Name             str
Industry         str
Inception    float64
Revenue          str
Expenses         str
Profit       float64
Growth           str
dtype: object

In [51]:
df3["Industry"] = df3["Industry"].replace("Technology", "nevil")
df3

    ID       Name Industry  Inception Revenue Expenses      Profit Growth
0  1.0          0        0     2009.0       0        0   5274553.0    30%
1  2.0  Stripfind        0     2010.0       0        0  11412916.0    20%
2  3.0          0        0     2012.0       0      NaN   3005820.0     7%
3  4.0          0        0     2013.0       0        0   6597557.0    26%
4  5.0  Techdrill        0     2009.0       0        0         NaN     8%
5  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN
6  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN
7  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN
8  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN
9  NaN        NaN      NaN        NaN     NaN      NaN         NaN    NaN

In [52]:
df1.replace("Financial", "Finance")

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4.0,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5.0,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6.0,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

## Interpolate()

In [53]:
df4 = pd.read_csv('Data//student_results - copy.csv')

df4

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.0,2.0,9.0,3.0,5,50.0
1,1002,10.0,6.0,8.0,2.0,0,80.0
2,1003,10.0,NaN,NaN,2.0,4,60.0
3,1004,11.0,NaN,NaN,1.0,5,45.0
4,1005,11.0,NaN,NaN,2.0,0,NaN
5,1006,11.0,10.0,7.0,0.0,0,NaN
6,1007,NaN,4.0,6.0,0.0,0,NaN
7,1008,NaN,10.0,NaN,NaN,0,90.0
8,1009,12.0,2.0,8.0,2.0,4,60.0
9,1010,12.0,6.0,9.0,1.0,0,85.0

In [54]:
 # fill only numeric value not char

df4.interpolate()

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.000000,2.0,9.00,3.0,5,50.00
1,1002,10.000000,6.0,8.00,2.0,0,80.00
2,1003,10.000000,7.0,7.75,2.0,4,60.00
3,1004,11.000000,8.0,7.50,1.0,5,45.00
4,1005,11.000000,9.0,7.25,2.0,0,56.25
5,1006,11.000000,10.0,7.00,0.0,0,67.50
6,1007,11.333333,4.0,6.00,0.0,0,78.75
7,1008,11.666667,10.0,7.00,1.0,0,90.00
8,1009,12.000000,2.0,8.00,2.0,4,60.00
9,1010,12.000000,6.0,9.00,1.0,0,85.00

In [55]:
df4.interpolate(mrthod = 'Linear')

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.000000,2.0,9.00,3.0,5,50.00
1,1002,10.000000,6.0,8.00,2.0,0,80.00
2,1003,10.000000,7.0,7.75,2.0,4,60.00
3,1004,11.000000,8.0,7.50,1.0,5,45.00
4,1005,11.000000,9.0,7.25,2.0,0,56.25
5,1006,11.000000,10.0,7.00,0.0,0,67.50
6,1007,11.333333,4.0,6.00,0.0,0,78.75
7,1008,11.666667,10.0,7.00,1.0,0,90.00
8,1009,12.000000,2.0,8.00,2.0,4,60.00
9,1010,12.000000,6.0,9.00,1.0,0,85.00

# loc and iloc

In [56]:
df5 = pd.read_csv('Data//student_results.xls')

df5

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [57]:
df5.loc[:]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [58]:
df5.loc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [59]:
df5.loc[1]

Student ID                1002
Class                       10
Study hrs                    6
Sleeping hrs                 8
Social Media usage hrs       2
Mobile Games hrs             0
Percantege                  80
Name: 1, dtype: int64

In [60]:
df5.loc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80

In [61]:
df5.loc[4, 'Class']

np.int64(11)

In [62]:
df5.loc[df5["Class"] < 11]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60

In [63]:
df5.loc[df5["Class"] < 11 , ['Percantege']]

   Percantege
0          50
1          80
2          60

# integer location based indexing   iloc

In [64]:
df5.iloc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [65]:
df5.iloc[[0]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50

In [66]:
df5.iloc[: , 0]

0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
6    1007
7    1008
8    1009
9    1010
Name: Student ID, dtype: int64

In [67]:
df5.iloc[[0 , 1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80